apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    app: nginx
  name: test-pod
spec:
  containers:
    - image: nginx:latest
      name: webserver
      resources:
        limits:
          cpu: "1"
          memory: "130Mi"
        requests:
          cpu: "0.5"
          memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
